FROM php:8.0-apache
WORKDIR /var/www/html/
RUN docker-php-ext-install mysqli && \
    docker-php-ext-enable mysqli &&\
    a2enmod authn_dbd && \
    pecl install -o -f redis && \
    rm -rf /tmp/pear && \
    docker-php-ext-enable redis && \
    apt-get update && \
    apt-get install -y libaprutil1-dbd-mysql && \
    service apache2 restart
COPY vendor /var/www/vendor
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd
COPY jpgraph /var/www/jpgraph