# Generated by Django 4.1.4 on 2022-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prac8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfloader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
