# Generated by Django 4.1.4 on 2022-12-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prac8', '0002_pdfloader'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfloader',
            name='title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
